spring.application.name=15_E_commerce_SpringBoot_Config_Server

# Standard port for Config Server
server.port=8888

# 1. Point to the root of your Git repository (must end in .git)
spring.cloud.config.server.git.uri=https://github.com/Nilesh123-45/Eclipse_Jenkins_CI-CD.git

# 2. Tell the server which folder holds the properties files
spring.cloud.config.server.git.search-paths=configs

# 3. Specify the exact branch name where the files are stored
spring.cloud.config.server.git.default-label=master