spring.application.name=07-irctc-booking-Rest_Profile_transactional_actuator_exception

spring.datasource.url=jdbc:mysql://localhost:3306/5th_jan_2026_batch
spring.datasource.username=root
spring.datasource.password=12345

# JDBC driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.profiles.active=qa

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.application.name=Payment Service
info.application.description=IRCTC Payment Microservice
info.application.version=1.0.0