spring.application.name=09-spring-boot-caching-redis-exception

# ---------------- MySQL ----------------
#spring.datasource.url=jdbc:mysql://localhost:3306/kodewala_practise_db?createDatabaseIfNotExist=true
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/kodewala_practise_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ---------------- Redis (Upstash) ----------------
spring.data.redis.host=humane-bengal-172898.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAqNiAAIgcDIyZTYzMzliMTU4YjE0OTBmODBjM2IyZGVjNDMzMGYxOA
spring.data.redis.ssl.enabled=true

# ---------------- OPTIONAL LOGS (cache hit/miss visibility) ----------------
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG