spring.application.name=15_ECOM_SpringBoot_API_Gateway

# Config Server Integration
spring.config.import=configserver:http://localhost:8888
server.port=8085

logging.level.org.springframework.cloud.gateway=DEBUG