server:
  port: 8085

spring:
  application:
    name: 01-Spring-Boot-Product-Category-API_Gateway

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      routes:
        - id: product-category-route
          uri: lb://01-Spring-Boot-Product-Category-Booking
          predicates:
            # This matches your exact @RequestMapping path
            - Path=/sellerManager/api/v1.4/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@ipKeyResolver}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true