spring.application.name=15_E_commerce_ProductService



# =========================================================
# SPRING CLOUD CONFIG SERVER
# =========================================================

spring.config.import=optional:configserver:http://localhost:8888


